import { Routes, Route } from 'react-router-dom'
import { useState } from 'react'
import './App.css'
import Header from './components/Header/Header'
import SovetLogo from './components/SovetLogo/SovetLogo'
import MainPage from './pages/MainPage/MainPage'
import NewsPage from './pages/NewsPage/NewsPage'
import AboutPage from './pages/AboutPage/AboutPage'
import EventsPage from './pages/EventsPage/EventsPage'
import SuggestionPage from './pages/SuggestionPage/SuggestionPage'
import MainLayout from './layouts/MainLayout/MainLayout'
import NewsDetailPage from './pages/NewsDetailPage/NewsDetailPage'
import EventDetailPage from './pages/EventDetailPage/EventDetailPage'

function App() {
  const [count, setCount] = useState(0)

  return (
    <Routes>
      <Route path="/" element={<MainLayout />}>
        <Route index element={<MainPage />} />
        <Route path="news" element={<NewsPage />} />
        <Route path="news/:id" element={<NewsDetailPage />} /> 
        <Route path="suggestions" element={<SuggestionPage />} />
        <Route path="event" element={<EventsPage />} />
        <Route path="event/:id" element={<EventDetailPage />} /> 
        <Route path="about" element={<AboutPage />} />
      </Route>
    </Routes>
    // <div className='app-container'>
    //   <Header></Header>
    //   <h2>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti amet accusantium placeat ipsum officia? Porro aperiam, tempora blanditiis iure alias iusto pariatur officiis sed animi, temporibus tenetur explicabo consectetur in.Enim, labore? Molestias aspernatur voluptate eaque vel, voluptas commodi eum velit magni reprehenderit laborum nihil quia, ullam optio dolor, ipsum natus? Debitis ipsum illum ducimus aspernatur molestias aut! Est, consequatur!Ratione facilis quasi ex aliquam labore quas, alias impedit necessitatibus ab? A id, molestias, odit officia deleniti ullam perspiciatis quod ut sunt maiores laboriosam dicta quo temporibus deserunt quibusdam natus!Impedit, neque eligendi corporis fugiat tempora ea quibusdam ducimus, praesentium aspernatur ipsam amet recusandae? Consequuntur saepe modi delectus recusandae nulla ipsam fugiat sed sunt expedita, a, aperiam reprehenderit veniam id.Sed incidunt provident optio perferendis non officiis consequuntur et unde commodi fuga. Commodi in quo laborum tenetur voluptatem repellendus excepturi reiciendis provident consectetur quidem veritatis dicta nulla, nemo officia voluptas.Laborum reprehenderit nostrum ipsa possimus culpa sit ipsum architecto repudiandae nobis cumque provident accusantium quam aut rerum, labore corrupti odio explicabo voluptatibus, commodi nulla hic praesentium! Numquam fugit eligendi quaerat!Ut eveniet cumque ratione aspernatur! Voluptas ab nihil vitae iure architecto est doloribus inventore consequuntur dignissimos nesciunt ratione facilis nemo tenetur, at, suscipit ipsam nulla beatae deserunt perferendis asperiores quam!Vitae ab eum placeat ipsum architecto blanditiis libero id voluptatem qui necessitatibus hic inventore eius autem itaque dolorum, recusandae modi dolor impedit, odio consequuntur suscipit error? Ea sequi impedit tenetur.Perspiciatis alias distinctio repudiandae consequuntur repellendus sed ducimus a omnis asperiores magnam ad tenetur excepturi recusandae iste repellat ipsum saepe animi in dolorum explicabo vel, voluptates exercitationem fuga. Similique, ipsa.Velit debitis repellat commodi porro, odio dolor incidunt, repellendus et inventore quas doloremque deserunt impedit ratione rem temporibus est, laboriosam consequuntur earum corporis officia natus sapiente mollitia quidem vero? Asperiores.</h2>
    //   <h2>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti amet accusantium placeat ipsum officia? Porro aperiam, tempora blanditiis iure alias iusto pariatur officiis sed animi, temporibus tenetur explicabo consectetur in.Enim, labore? Molestias aspernatur voluptate eaque vel, voluptas commodi eum velit magni reprehenderit laborum nihil quia, ullam optio dolor, ipsum natus? Debitis ipsum illum ducimus aspernatur molestias aut! Est, consequatur!Ratione facilis quasi ex aliquam labore quas, alias impedit necessitatibus ab? A id, molestias, odit officia deleniti ullam perspiciatis quod ut sunt maiores laboriosam dicta quo temporibus deserunt quibusdam natus!Impedit, neque eligendi corporis fugiat tempora ea quibusdam ducimus, praesentium aspernatur ipsam amet recusandae? Consequuntur saepe modi delectus recusandae nulla ipsam fugiat sed sunt expedita, a, aperiam reprehenderit veniam id.Sed incidunt provident optio perferendis non officiis consequuntur et unde commodi fuga. Commodi in quo laborum tenetur voluptatem repellendus excepturi reiciendis provident consectetur quidem veritatis dicta nulla, nemo officia voluptas.Laborum reprehenderit nostrum ipsa possimus culpa sit ipsum architecto repudiandae nobis cumque provident accusantium quam aut rerum, labore corrupti odio explicabo voluptatibus, commodi nulla hic praesentium! Numquam fugit eligendi quaerat!Ut eveniet cumque ratione aspernatur! Voluptas ab nihil vitae iure architecto est doloribus inventore consequuntur dignissimos nesciunt ratione facilis nemo tenetur, at, suscipit ipsam nulla beatae deserunt perferendis asperiores quam!Vitae ab eum placeat ipsum architecto blanditiis libero id voluptatem qui necessitatibus hic inventore eius autem itaque dolorum, recusandae modi dolor impedit, odio consequuntur suscipit error? Ea sequi impedit tenetur.Perspiciatis alias distinctio repudiandae consequuntur repellendus sed ducimus a omnis asperiores magnam ad tenetur excepturi recusandae iste repellat ipsum saepe animi in dolorum explicabo vel, voluptates exercitationem fuga. Similique, ipsa.Velit debitis repellat commodi porro, odio dolor incidunt, repellendus et inventore quas doloremque deserunt impedit ratione rem temporibus est, laboriosam consequuntur earum corporis officia natus sapiente mollitia quidem vero? Asperiores.</h2>
    //   <h2>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti amet accusantium placeat ipsum officia? Porro aperiam, tempora blanditiis iure alias iusto pariatur officiis sed animi, temporibus tenetur explicabo consectetur in.Enim, labore? Molestias aspernatur voluptate eaque vel, voluptas commodi eum velit magni reprehenderit laborum nihil quia, ullam optio dolor, ipsum natus? Debitis ipsum illum ducimus aspernatur molestias aut! Est, consequatur!Ratione facilis quasi ex aliquam labore quas, alias impedit necessitatibus ab? A id, molestias, odit officia deleniti ullam perspiciatis quod ut sunt maiores laboriosam dicta quo temporibus deserunt quibusdam natus!Impedit, neque eligendi corporis fugiat tempora ea quibusdam ducimus, praesentium aspernatur ipsam amet recusandae? Consequuntur saepe modi delectus recusandae nulla ipsam fugiat sed sunt expedita, a, aperiam reprehenderit veniam id.Sed incidunt provident optio perferendis non officiis consequuntur et unde commodi fuga. Commodi in quo laborum tenetur voluptatem repellendus excepturi reiciendis provident consectetur quidem veritatis dicta nulla, nemo officia voluptas.Laborum reprehenderit nostrum ipsa possimus culpa sit ipsum architecto repudiandae nobis cumque provident accusantium quam aut rerum, labore corrupti odio explicabo voluptatibus, commodi nulla hic praesentium! Numquam fugit eligendi quaerat!Ut eveniet cumque ratione aspernatur! Voluptas ab nihil vitae iure architecto est doloribus inventore consequuntur dignissimos nesciunt ratione facilis nemo tenetur, at, suscipit ipsam nulla beatae deserunt perferendis asperiores quam!Vitae ab eum placeat ipsum architecto blanditiis libero id voluptatem qui necessitatibus hic inventore eius autem itaque dolorum, recusandae modi dolor impedit, odio consequuntur suscipit error? Ea sequi impedit tenetur.Perspiciatis alias distinctio repudiandae consequuntur repellendus sed ducimus a omnis asperiores magnam ad tenetur excepturi recusandae iste repellat ipsum saepe animi in dolorum explicabo vel, voluptates exercitationem fuga. Similique, ipsa.Velit debitis repellat commodi porro, odio dolor incidunt, repellendus et inventore quas doloremque deserunt impedit ratione rem temporibus est, laboriosam consequuntur earum corporis officia natus sapiente mollitia quidem vero? Asperiores.</h2>

    //   {/* <script src="https://forms.yandex.ru/_static/embed.js"></script><iframe src="https://forms.yandex.ru/u/69f50cd0d04688310e7e297b?iframe=1" frameBorder="0" name="ya-form-69f50cd0d04688310e7e297b" width="650" height={"1000"}></iframe> */}
    // </div>
  )
}

export default App
